import type { AdapterModel } from "@paperclipai/adapter-utils";

/**
 * Offline fallback when `agent models` is unavailable.
 * Regenerate: node packages/adapters/cursor-local/scripts/sync-model-catalog.mjs
 * Snapshot: 2026-05-19 (109 models from Cursor Agent CLI).
 */
/** Routic 对齐 Cursor 2.5 代；CLI 列表仍可能给 composer-2-fast 标 (default)。 */
export const CURSOR_CLI_DEFAULT_MODEL_ID = "composer-2.5-fast";

export const CURSOR_FALLBACK_MODELS: readonly AdapterModel[] = [
  { id: "auto", label: "Auto" },
  { id: "composer-2-fast", label: "Composer 2 Fast" },
  { id: "composer-2", label: "Composer 2" },
  { id: "gpt-5.3-codex-low", label: "Codex 5.3 Low" },
  { id: "gpt-5.3-codex-low-fast", label: "Codex 5.3 Low Fast" },
  { id: "gpt-5.3-codex", label: "Codex 5.3" },
  { id: "gpt-5.3-codex-fast", label: "Codex 5.3 Fast" },
  { id: "gpt-5.3-codex-high", label: "Codex 5.3 High" },
  { id: "gpt-5.3-codex-high-fast", label: "Codex 5.3 High Fast" },
  { id: "gpt-5.3-codex-xhigh", label: "Codex 5.3 Extra High" },
  { id: "gpt-5.3-codex-xhigh-fast", label: "Codex 5.3 Extra High Fast" },
  { id: "gpt-5.2", label: "GPT-5.2" },
  { id: "gpt-5.2-codex-low", label: "Codex 5.2 Low" },
  { id: "gpt-5.2-codex-low-fast", label: "Codex 5.2 Low Fast" },
  { id: "gpt-5.2-codex", label: "Codex 5.2" },
  { id: "gpt-5.2-codex-fast", label: "Codex 5.2 Fast" },
  { id: "gpt-5.2-codex-high", label: "Codex 5.2 High" },
  { id: "gpt-5.2-codex-high-fast", label: "Codex 5.2 High Fast" },
  { id: "gpt-5.2-codex-xhigh", label: "Codex 5.2 Extra High" },
  { id: "gpt-5.2-codex-xhigh-fast", label: "Codex 5.2 Extra High Fast" },
  { id: "gpt-5.1-codex-max-low", label: "Codex 5.1 Max Low" },
  { id: "gpt-5.1-codex-max-low-fast", label: "Codex 5.1 Max Low Fast" },
  { id: "gpt-5.1-codex-max-medium", label: "Codex 5.1 Max" },
  { id: "gpt-5.1-codex-max-medium-fast", label: "Codex 5.1 Max Medium Fast" },
  { id: "gpt-5.1-codex-max-high", label: "Codex 5.1 Max High" },
  { id: "gpt-5.1-codex-max-high-fast", label: "Codex 5.1 Max High Fast" },
  { id: "gpt-5.1-codex-max-xhigh", label: "Codex 5.1 Max Extra High" },
  { id: "gpt-5.1-codex-max-xhigh-fast", label: "Codex 5.1 Max Extra High Fast" },
  { id: "composer-2.5", label: "Composer 2.5" },
  { id: "gpt-5.5-high", label: "GPT-5.5 1M High" },
  { id: "gpt-5.5-high-fast", label: "GPT-5.5 High Fast" },
  { id: "claude-opus-4-7-thinking-high", label: "Opus 4.7 1M High Thinking" },
  { id: "gpt-5.4-high", label: "GPT-5.4 1M High" },
  { id: "gpt-5.4-high-fast", label: "GPT-5.4 High Fast" },
  { id: "claude-4.6-opus-high-thinking", label: "Opus 4.6 1M Thinking" },
  { id: "claude-4.6-opus-high-thinking-fast", label: "Opus 4.6 1M Thinking Fast" },
  { id: "composer-2.5-fast", label: "Composer 2.5 Fast" },
  { id: "gpt-5.5-none", label: "GPT-5.5 1M None" },
  { id: "gpt-5.5-none-fast", label: "GPT-5.5 None Fast" },
  { id: "gpt-5.5-low", label: "GPT-5.5 1M Low" },
  { id: "gpt-5.5-low-fast", label: "GPT-5.5 Low Fast" },
  { id: "gpt-5.5-medium", label: "GPT-5.5 1M" },
  { id: "gpt-5.5-medium-fast", label: "GPT-5.5 Fast" },
  { id: "gpt-5.5-extra-high", label: "GPT-5.5 1M Extra High" },
  { id: "gpt-5.5-extra-high-fast", label: "GPT-5.5 Extra High Fast" },
  { id: "claude-4.6-sonnet-medium", label: "Sonnet 4.6 1M" },
  { id: "claude-4.6-sonnet-medium-thinking", label: "Sonnet 4.6 1M Thinking" },
  { id: "claude-opus-4-7-low", label: "Opus 4.7 1M Low" },
  { id: "claude-opus-4-7-low-fast", label: "Opus 4.7 1M Low Fast" },
  { id: "claude-opus-4-7-medium", label: "Opus 4.7 1M Medium" },
  { id: "claude-opus-4-7-medium-fast", label: "Opus 4.7 1M Medium Fast" },
  { id: "claude-opus-4-7-high", label: "Opus 4.7 1M High" },
  { id: "claude-opus-4-7-high-fast", label: "Opus 4.7 1M High Fast" },
  { id: "claude-opus-4-7-xhigh", label: "Opus 4.7 1M" },
  { id: "claude-opus-4-7-xhigh-fast", label: "Opus 4.7 1M Fast" },
  { id: "claude-opus-4-7-max", label: "Opus 4.7 1M Max" },
  { id: "claude-opus-4-7-max-fast", label: "Opus 4.7 1M Max Fast" },
  { id: "claude-opus-4-7-thinking-low", label: "Opus 4.7 1M Low Thinking" },
  { id: "claude-opus-4-7-thinking-low-fast", label: "Opus 4.7 1M Low Thinking Fast" },
  { id: "claude-opus-4-7-thinking-medium", label: "Opus 4.7 1M Medium Thinking" },
  { id: "claude-opus-4-7-thinking-medium-fast", label: "Opus 4.7 1M Medium Thinking Fast" },
  { id: "claude-opus-4-7-thinking-high-fast", label: "Opus 4.7 1M High Thinking Fast" },
  { id: "claude-opus-4-7-thinking-xhigh", label: "Opus 4.7 1M Thinking" },
  { id: "claude-opus-4-7-thinking-xhigh-fast", label: "Opus 4.7 1M Thinking Fast" },
  { id: "claude-opus-4-7-thinking-max", label: "Opus 4.7 1M Max Thinking" },
  { id: "claude-opus-4-7-thinking-max-fast", label: "Opus 4.7 1M Max Thinking Fast" },
  { id: "grok-4.3", label: "Grok 4.3 1M" },
  { id: "gpt-5.4-low", label: "GPT-5.4 1M Low" },
  { id: "gpt-5.4-medium", label: "GPT-5.4 1M" },
  { id: "gpt-5.4-medium-fast", label: "GPT-5.4 Fast" },
  { id: "gpt-5.4-xhigh", label: "GPT-5.4 1M Extra High" },
  { id: "gpt-5.4-xhigh-fast", label: "GPT-5.4 Extra High Fast" },
  { id: "claude-4.6-opus-high", label: "Opus 4.6 1M" },
  { id: "claude-4.6-opus-max", label: "Opus 4.6 1M Max" },
  { id: "claude-4.6-opus-max-thinking", label: "Opus 4.6 1M Max Thinking" },
  { id: "claude-4.6-opus-max-thinking-fast", label: "Opus 4.6 1M Max Thinking Fast" },
  { id: "claude-4.5-opus-high", label: "Opus 4.5" },
  { id: "claude-4.5-opus-high-thinking", label: "Opus 4.5 Thinking" },
  { id: "gpt-5.2-low", label: "GPT-5.2 Low" },
  { id: "gpt-5.2-low-fast", label: "GPT-5.2 Low Fast" },
  { id: "gpt-5.2-fast", label: "GPT-5.2 Fast" },
  { id: "gpt-5.2-high", label: "GPT-5.2 High" },
  { id: "gpt-5.2-high-fast", label: "GPT-5.2 High Fast" },
  { id: "gpt-5.2-xhigh", label: "GPT-5.2 Extra High" },
  { id: "gpt-5.2-xhigh-fast", label: "GPT-5.2 Extra High Fast" },
  { id: "gemini-3.1-pro", label: "Gemini 3.1 Pro" },
  { id: "gpt-5.4-mini-none", label: "GPT-5.4 Mini None" },
  { id: "gpt-5.4-mini-low", label: "GPT-5.4 Mini Low" },
  { id: "gpt-5.4-mini-medium", label: "GPT-5.4 Mini" },
  { id: "gpt-5.4-mini-high", label: "GPT-5.4 Mini High" },
  { id: "gpt-5.4-mini-xhigh", label: "GPT-5.4 Mini Extra High" },
  { id: "gpt-5.4-nano-none", label: "GPT-5.4 Nano None" },
  { id: "gpt-5.4-nano-low", label: "GPT-5.4 Nano Low" },
  { id: "gpt-5.4-nano-medium", label: "GPT-5.4 Nano" },
  { id: "gpt-5.4-nano-high", label: "GPT-5.4 Nano High" },
  { id: "gpt-5.4-nano-xhigh", label: "GPT-5.4 Nano Extra High" },
  { id: "claude-4.5-sonnet", label: "Sonnet 4.5" },
  { id: "claude-4.5-sonnet-thinking", label: "Sonnet 4.5 Thinking" },
  { id: "gpt-5.1-low", label: "GPT-5.1 Low" },
  { id: "gpt-5.1", label: "GPT-5.1" },
  { id: "gpt-5.1-high", label: "GPT-5.1 High" },
  { id: "gemini-3-flash", label: "Gemini 3 Flash" },
  { id: "gpt-5.1-codex-mini-low", label: "Codex 5.1 Mini Low" },
  { id: "gpt-5.1-codex-mini", label: "Codex 5.1 Mini" },
  { id: "gpt-5.1-codex-mini-high", label: "Codex 5.1 Mini High" },
  { id: "claude-4-sonnet", label: "Sonnet 4" },
  { id: "claude-4-sonnet-thinking", label: "Sonnet 4 Thinking" },
  { id: "gpt-5-mini", label: "GPT-5 Mini" },
  { id: "kimi-k2.5", label: "Kimi K2.5" },
] as const;

export const models: AdapterModel[] = [...CURSOR_FALLBACK_MODELS];
